WITH AVG_DAILY_AIR_QUALITY AS (
    SELECT 
	SAQ.CITY,
	SAQ.EXTRACTED_AT,
	DATE_TRUNC('DAY', SAQ.OBSERVED_AT)::DATE AS FORECAST_DAY,
	SAQ.DUST_UNITS,
	ROUND(AVG(SAQ.DUST_VALUE)::NUMERIC, 2) AS AVG_DAILY_DUST_VALUE,
	SAQ.OZONE_UNITS,
	ROUND(AVG(SAQ.OZONE)::NUMERIC, 2) AS AVG_DAILY_OZONE,
	SAQ.METHANE_UNITS,
	ROUND(AVG(SAQ.METHANE)::NUMERIC, 2) AS AVG_DAILY_METHANE,
	ROUND(AVG(SAQ.UV_INDEX)::NUMERIC, 2) AS AVG_DAILY_UV_INDEX,
	SAQ.CARBON_UNITS,
	ROUND(AVG(SAQ.CARBON_DIOXIDE)::NUMERIC, 2) AS AVG_DAILY_CARBON
FROM {{ref('stg_air_quality')}} SAQ
GROUP BY 
	SAQ.CITY,
	SAQ.EXTRACTED_AT,
	SAQ.DUST_UNITS,
	SAQ.OZONE_UNITS,
	SAQ.METHANE_UNITS,
	SAQ.CARBON_UNITS,
	DATE_TRUNC('DAY', SAQ.OBSERVED_AT)
)

SELECT *
FROM AVG_DAILY_AIR_QUALITY