WITH AVG_DAILY_TEMPERATURE AS (
    SELECT 
	SF.CITY,
	SF.EXTRACTED_AT,
	SF.TEMPERATURE_UNITS,
	DATE_TRUNC('DAY', SF.OBSERVED_AT)::DATE AS FORECAST_DAY,
	ROUND(AVG(SF.TEMPERATURE)::NUMERIC, 2) AS AVG_DAILY_TEMPERATURE
FROM {{ref('stg_forecast')}} SF
GROUP BY SF.CITY, SF.EXTRACTED_AT, SF.TEMPERATURE_UNITS, DATE_TRUNC('DAY', SF.OBSERVED_AT)
)

SELECT *
FROM AVG_DAILY_TEMPERATURE