WITH HOURLY AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		FORECAST_RESPONSE
	FROM {{source('data-pipeline', 'forecast_open_meteo')}}
),

TIME_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::TIMESTAMP AS OBSERVED_AT,
		FORECAST_RESPONSE -> 'hourly_units' ->> 'time' AS TIME_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(FORECAST_RESPONSE -> 'hourly' -> 'time') WITH ORDINALITY AS T(VALUE, IDX)
),

RAIN_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS RAIN_MM,
		FORECAST_RESPONSE -> 'hourly_units' ->> 'rain' RAIN_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(FORECAST_RESPONSE -> 'hourly' -> 'rain') WITH ORDINALITY AS T(VALUE, IDX)
),

TEMPERATURE_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS TEMPERATURE,
		FORECAST_RESPONSE -> 'hourly_units' ->> 'temperature_2m' TEMPERATURE_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(FORECAST_RESPONSE -> 'hourly' -> 'temperature_2m') WITH ORDINALITY AS T(VALUE, IDX)
)

SELECT *
FROM TIME_EXPANDED TIME
LEFT JOIN RAIN_EXPANDED RAIN USING (CITY, EXTRACTED_AT, IDX)
LEFT JOIN TEMPERATURE_EXPANDED TEMP USING (CITY, EXTRACTED_AT, IDX)
