WITH HOURLY AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		AIR_QUALITY_RESPONSE
    FROM {{ source('data-pipeline', 'air_quality_open_meteo') }}
),

TIME_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::TIMESTAMP AS OBSERVED_AT,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'time' AS TIME_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'time') WITH ORDINALITY AS T(VALUE, IDX)
),

DUST_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS DUST_VALUE,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'dust' AS DUST_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'dust') WITH ORDINALITY AS T(VALUE, IDX)
),

OZONE_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS OZONE,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'ozone' AS OZONE_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'ozone') WITH ORDINALITY AS T(VALUE, IDX)
),

METHANE_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS METHANE,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'methane' AS METHANE_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'methane') WITH ORDINALITY AS T(VALUE, IDX)
),

UV_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS UV_INDEX,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'uv_index' AS UV_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'uv_index') WITH ORDINALITY AS T(VALUE, IDX)
),

CARBON_EXPANDED AS (
	SELECT
		CITY,
		EXTRACTED_AT,
		IDX,
		VALUE::FLOAT AS CARBON_DIOXIDE,
		AIR_QUALITY_RESPONSE -> 'hourly_units' ->> 'carbon_dioxide' AS CARBON_UNITS
	FROM HOURLY,
	LATERAL JSONB_ARRAY_ELEMENTS_TEXT(AIR_QUALITY_RESPONSE  -> 'hourly' -> 'carbon_dioxide') WITH ORDINALITY AS T(VALUE, IDX)
)

SELECT *
FROM TIME_EXPANDED TIME
LEFT JOIN DUST_EXPANDED DUST USING (CITY, EXTRACTED_AT, IDX)
LEFT JOIN OZONE_EXPANDED OZONE USING (CITY, EXTRACTED_AT, IDX)
LEFT JOIN METHANE_EXPANDED METHANE USING (CITY, EXTRACTED_AT, IDX)
LEFT JOIN UV_EXPANDED UV USING (CITY, EXTRACTED_AT, IDX)
LEFT JOIN CARBON_EXPANDED CARBON USING (CITY, EXTRACTED_AT, IDX)